### ISSUE TITLE
osx-arm64 rerender not succesful, flex and bison successfully installed but not found?

### ISSUE THREAD

**Issue by willend** [conda-forge/mcstas-suite-feedstock#1]
### Comment:

@conda-forge/help-osx-arm64 

I tried enabling cross-compilation on this feedstock for e.g. osx-arm64 and requested a re-render, but somehow the compile-time dependencies of bison and flex do not make it to the cross-compile environment, see
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=832888&view=logs&j=ced5d8de-8227-5f3f-33a1-45cf1592c45a&t=f7bcb349-6dca-53ba-d88d-1d9963e119ba  

(The strange thing is that in line 78-82 these dependencies are successfully installed:
    bison:    3.8.2-h151c81c_0     conda-forge
    flex:     2.6.4-h1474e2a_1004  conda-forge
    libcxx:   16.0.6-h4653b0c_0    conda-forge
    libiconv: 1.17-he4db4b2_0      conda-forge
    m4:       1.4.18-h642e427_1001 conda-forge

In line 258-275 there is an issue detecting them via CMake, but in line 278 they are reported as found?)

Am I overlooking something obvious, e.g. do I need some extra section for cross-compilation in https://github.com/conda-forge/mcstas-suite-feedstock/blob/main/recipe/meta.yaml ?)

**Comment by isuruf** [comment]
@willend, please use PRs from a fork instead of pushing to main or any other branch in this repo. Send a PR to enable osx-arm64, and tag me there

**Comment by willend** [comment]
@isuruf I guess I should initially revert my current modification to conda-forge.yml on main then?

**Comment by isuruf** [comment]
Yes

**Comment by willend** [comment]
Compilation achieved thanks to your assistance @isuruf, so I am closing. For sake of internal knowledge sharing I will let @tkittel merge the PR.
